/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    'node_modules/flowbite-react/lib/esm/**/*.js',
  ],
  theme: {
    extend: {},
  },
  plugins: [require('flowbite/plugin')],
  safelist: [
    'bg-[rgba(255,255,0,0.2)]',
    'bg-[rgba(255,0,0,0.2)]',
    'bg-[#dafc00]',
    'bg-[transparent]',
    'enabled:hover:bg-[#dafc00]',
    'hover:[&>button]:bg-[#caa4ea]',
    '[&>div>div>label]:bg-[#8442b9]',
    '[&>div>p]:bg-[#8442b9]',
    'hover:bg-[#dafc00]/25',
    'bg-[#dafc00]/50',
    'bg-[rgba(255,255,0,0.2)]',
    'bg-[rgba(255,0,0,0.2)]',
    '[&>div]:bg-[#dafc00]',
    '[&>div>div]:bg-[#dafc00]',
    'text-[#dafc00]',
    'text-[#a556e6]',
    'text-[#8442b9]',
    'enabled:hover:text-[#8442b9]',
    '[&>button]:text-[#a556e6]',
    'hover:[&>button]:text-[#8442b9]',
    '[&>h3]:text-[#8442b9]',
    'dark:text-[#dafc00]',
    'peer-focus:text-[#dafc00]',
    'peer-focus:dark:text-[#dafc00]',
    '[&>div]:text-[#dafc00]',
    '[&>div]:dark:text-[#dafc00]',
    'border-x-0',
    'border-x-4',
    'border-[#dafc00]',
    'dark:border-[#dafc00]',
    'dark:focus:border-[#dafc00]',
    'focus:border-[#dafc00]',
  ],
}
